### ISSUE TITLE
Add custom emojis category help

### ISSUE THREAD

**Issue by WilliamAcosta1** [ZumitoTeam/zumito-bot#134]
- Description problem:
Currently you can not place perzonalized emojis in each category I know it is something aesthetic but it would be great as well as the categories that come out in the help message should be the same as it comes out in the drop down menu.

- Imegen of evidence:

![image](https://github.com/ZumitoTeam/zumito-bot/assets/105233030/c039be1a-ed8c-4365-a495-b930f9e5d0b8)

For some reason if perzonalized emojis are included in the category it causes a problem that shuts down the bot my proposal is to see what is the cause and be able to fix it.

![image](https://github.com/ZumitoTeam/zumito-bot/assets/105233030/746fd4cc-27d4-444e-9733-c569b90129cd)

When we select a category as it is appreciated in the image the ideal thing is that it goes out first its emoji and name of the category that is to say that each one is a separate variable.

**Comment by fernandomema** [comment]
Seems like discord doesn't render custom emojis on dropdowns

![image](https://github.com/ZumitoTeam/zumito-bot/assets/3452041/d0e74ed8-f408-49ec-a533-a550d3eac0d7)
