### ISSUE TITLE
Add a button to close the help menu

### ISSUE THREAD

**Issue by WilliamAcosta1** [ZumitoTeam/zumito-bot#135]
- Description problem:
The help menu is not possible to close it currently ideally would be to add a button to remove the help menu message from any alias either when querying a specific command.

- Imegen of evidence:

![image](https://github.com/ZumitoTeam/zumito-bot/assets/105233030/febdc417-f7ad-4cec-9886-7795a721e601)

Can be these two buttons

**Comment by fernandomema** [comment]
@WilliamAcosta1 Where those buttons should go? Under the category dropdown?

**Comment by WilliamAcosta1** [comment]
> @WilliamAcosta1 Where those buttons should go? Under the category dropdown?

Yes, it should go under the category menu.
